- name: hello world
  hosts: local
  connection: local #No need to giving th username & password
  tasks:
  - name: print hello world
    ansible.builtin.debug:
      msg: "Hello World"

# ansible-playbook -i inventory.ini 02-hello-world.yaml



