- name: play and task level variables
  hosts: local
  connection: local
  vars: 
    COURSE: DevOps with AWS
    DURATION: 10HR
    TRAINER: Siva
  tasks:
  - name: print course information
    vars:
      COURSE: Ansible # here the task level is variable override the play level varibales
    ansible.builtin.debug:
      mag: "Hello {{ COURSE }} , Duration is : {{ DURATION }} ,Trainer is {{ TRAINER }}"

  - name: print course information
    ansible.builtin.debug:
      mag: "Hello {{ COURSE }} , Duration is : {{ DURATION }} ,Trainer is {{ TRAINER }}"

