- name: variables from args
  hosts: local
  connection: local
  tasks:
  - name: print course info
    ansible.builtin.debug:
      msg: "Hello I am learning {{ COURSE }}, duration is {{ DURATION }}, Trainer is {{ TRAINER }}"

# pass the variable via command line args 

# ansible-playbook -i inventory -e "COURSE-ARGS" -e "DURATION=10mints" -e "TRAINER=Siva"

